/*
* generated by Xtext
*/
package com.ponta027.xtext.statemachine.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/ponta027/xtext/statemachine/parser/antlr/internal/InternalDsl.tokens");
	}
}
