/*
 * generated by Xtext
 */
package com.ponta027.xtext.statemachine.ui.contentassist

import com.ponta027.xtext.statemachine.ui.contentassist.AbstractDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DslProposalProvider extends AbstractDslProposalProvider {
}
